server:
  port: 8280

auth-server: http://localhost:8090

security:
  oauth2:
    client:
      client-id: ms-client
      client-secret: aa
      access-token-uri: http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorize

    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key

messages:
  base-uri: http://localhost:8091/messages



logging:
  level:
    org:
      springframework:
        security: DEBUG
