server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://10.6.172.179:3306/permission?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 8
      maximum-pool-size: 16
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariDataPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual

logging:
  level:
    org:
      springframework:
        security: DEBUG

#redis:
#  database: 2
#  host: localhost
#  port: 32768
#  password: 1qaz@WSX
#  jedis:
#    pool:
#      max-active: 8
#      max-idle: 8
#      min-idle: 0
#  timeout: 100ms