server:
  port: 8090

logging:
  level:
    org:
      springframework:
        security: DEBUG

#redis:
#  database: 2
#  host: localhost
#  port: 32768
#  password: 1qaz@WSX
#  jedis:
#    pool:
#      max-active: 8
#      max-idle: 8
#      min-idle: 0
#  timeout: 100ms