server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/admin_auth?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 16
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariDataPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual
    local:
      jdbc-url: jdbc:mysql://localhost:3308/admin_auth?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123
      type: com.zaxxer.hikari.HikariDataSource
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: templates/**
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    ip-address: localhost

swagger:
  enable: true
  title: 字典管理
  pkg: com.coin.msdict.web.controller


