spring:
  profiles:
    active: dev

  application:
    name: ms-dict

  thymeleaf:
    suffix: .html
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    cache: false
    mode: HTML

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


dict:
  cache:
    islocal: true