server:
  port: 8281

auth-server: http://localhost:8090

security:
  oauth2:
    client:
      client-id: ms-client
      client-secret: aa
      grant-type: authorization_code
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
      scope: read, write
      pre-established-redirect-uri: http://localhost:8280/authorized
      use-current-uri: false
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key

messages:
  base-uri: http://localhost:8091/messages

