server:
  port: 8384
  servlet:
    context-path: /crm

cas:
  server:
    name: http://mmoayyed.unicon.net:8443
    url:
      prefix: ${cas.server.name}/cas
      login: ${cas.server.url.prefix}/login
      logout: ${cas.server.url.prefix}/logout?service=${cas.client.server.url.prefix}

  client:
    server:
      name: http://mmoayyed.unicof.net:${server.port}
      url:
        prefix: ${cas.client.server.name}${server.servlet.context-path}

